import videosData from "../data/videos.json";

export const CATEGORIES = [
  { id: "ai", label: "AI" },
  { id: "developer-tools", label: "Developer tools" },
  { id: "design", label: "Design" },
  { id: "productivity", label: "Productivity" },
  { id: "consumer", label: "Consumer" },
  { id: "hardware", label: "Hardware" },
  { id: "other", label: "Other" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export interface LaunchVideo {
  id: string;
  slug: string;
  title: string;
  product: string;
  company: string;
  description: string;
  category: CategoryId;
  tags: string[];
  tweetUrl: string;
  tweetId: string;
  authorName: string;
  authorHandle: string;
  authorAvatar: string | null;
  /** Local 16:9 poster under /public */
  poster: string;
  /**
   * Original amplify MP4 on X's CDN. Used for poster/stream capture, and
   * for in-site playback via the video proxy (see playbackUrl) — direct
   * URLs 403 in browsers because X's CDN rejects non-Twitter referers.
   */
  videoUrl: string | null;
  /**
   * Optional playback override. When omitted, players use the video proxy
   * (PUBLIC_VIDEO_PROXY_BASE) or fall back to `/streams/{slug}.mp4`.
   */
  streamUrl?: string | null;
  publishedAt: string;
  durationSeconds: number | null;
  featured: boolean;
  status: "published" | "draft";
}

export const allVideos = videosData as LaunchVideo[];

export const publishedVideos = allVideos
  .filter((video) => video.status === "published")
  .slice()
  .sort(
    (left, right) =>
      Date.parse(right.publishedAt) - Date.parse(left.publishedAt) ||
      left.title.localeCompare(right.title),
  );

export function categoryLabel(category: CategoryId) {
  return CATEGORIES.find((item) => item.id === category)?.label ?? category;
}

export function formatPublishedAt(iso: string) {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

export function formatDuration(seconds: number | null) {
  if (seconds == null || seconds <= 0) return null;
  const mins = Math.floor(seconds / 60);
  const secs = Math.round(seconds % 60);
  return `${mins}:${String(secs).padStart(2, "0")}`;
}

export function tweetPath(video: LaunchVideo) {
  return `/videos/${video.slug}/`;
}

export function xProfileUrl(handle: string) {
  return `https://x.com/${handle.replace(/^@/, "")}`;
}

/**
 * Playback source for in-site HTML5 playback.
 *
 * Precedence:
 *  1. `streamUrl` — explicit per-video override.
 *  2. The video proxy (PUBLIC_VIDEO_PROXY_BASE) wrapping the original
 *     video.twimg.com URL. X's CDN 403s any non-Twitter Referer, and
 *     browsers always attach one to <video> requests, so direct URLs do
 *     not play in-site; the proxy fetches server-side without a Referer
 *     (same trick as proxy.minttr.com, but self-hosted on Cloudflare
 *     Workers — see workers/video-proxy).
 *  3. Local same-origin stream under /streams (dev fallback, generated by
 *     scripts/capture-posters.mjs; gitignored).
 */
export function playbackUrl(video: LaunchVideo) {
  if (video.streamUrl) return video.streamUrl;
  const proxyBase = import.meta.env.PUBLIC_VIDEO_PROXY_BASE;
  if (proxyBase && video.videoUrl) {
    return `${proxyBase}/?url=${encodeURIComponent(video.videoUrl)}`;
  }
  return `/streams/${video.slug}.mp4`;
}

export function normalizeTweetUrl(url: string) {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname.replace(/^www\./, "");
    if (host === "twitter.com" || host === "x.com" || host === "mobile.twitter.com") {
      parsed.hostname = "x.com";
      parsed.search = "";
      parsed.hash = "";
      return parsed.toString().replace(/\/$/, "");
    }
  } catch {
    // fall through
  }
  return url;
}

function descriptionTerms(video: LaunchVideo) {
  return new Set(
    [video.title, video.product, video.company, video.description, ...video.tags]
      .join(" ")
      .toLocaleLowerCase()
      .match(/[a-z0-9]+/g)
      ?.filter((term) => term.length > 2) ?? [],
  );
}

export function getSimilarVideos(
  current: LaunchVideo,
  candidates: LaunchVideo[] = publishedVideos,
  limit = 4,
) {
  const currentTerms = descriptionTerms(current);

  return candidates
    .filter((candidate) => candidate.slug !== current.slug)
    .map((candidate) => {
      const sameCategory = candidate.category === current.category ? 100 : 0;
      const sharedTerms = [...descriptionTerms(candidate)].filter((term) =>
        currentTerms.has(term),
      ).length;
      return {
        video: candidate,
        score: sameCategory + sharedTerms * 4,
      };
    })
    .sort(
      (left, right) =>
        right.score - left.score ||
        Date.parse(right.video.publishedAt) - Date.parse(left.video.publishedAt),
    )
    .slice(0, Math.max(0, limit))
    .map(({ video }) => video);
}
